server:
  name: AnythingMarketService
  port: 8088

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/market_db
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 10
      queue_capacity: 10
      name:
        prefix: async-service-
      keep_alive_seconds: 100
